package com.kjnext.dmart.hibernate;



/**
 * AdminDetails generated by MyEclipse - Hibernate Tools
 */

public class AdminDetails  implements java.io.Serializable {


    // Fields    

     private Integer userEmpId;
     private Location location;
     private Users users;
     private String adminFirstName;
     private String adminLastName;
     private String adminAddress;
     private String adminEmail;
     private String adminContactNo;
     private String adminStatus;


    // Constructors

    /** default constructor */
    public AdminDetails() {
    }

	/** minimal constructor */
    public AdminDetails(Integer userEmpId) {
        this.userEmpId = userEmpId;
    }
    
    /** full constructor */
    public AdminDetails(Integer userEmpId, Location location, Users users, String adminFirstName, String adminLastName, String adminAddress, String adminEmail, String adminContactNo, String adminStatus) {
        this.userEmpId = userEmpId;
        this.location = location;
        this.users = users;
        this.adminFirstName = adminFirstName;
        this.adminLastName = adminLastName;
        this.adminAddress = adminAddress;
        this.adminEmail = adminEmail;
        this.adminContactNo = adminContactNo;
        this.adminStatus = adminStatus;
    }

   
    // Property accessors

    public Integer getUserEmpId() {
        return this.userEmpId;
    }
    
    public void setUserEmpId(Integer userEmpId) {
        this.userEmpId = userEmpId;
    }

    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    public String getAdminFirstName() {
        return this.adminFirstName;
    }
    
    public void setAdminFirstName(String adminFirstName) {
        this.adminFirstName = adminFirstName;
    }

    public String getAdminLastName() {
        return this.adminLastName;
    }
    
    public void setAdminLastName(String adminLastName) {
        this.adminLastName = adminLastName;
    }

    public String getAdminAddress() {
        return this.adminAddress;
    }
    
    public void setAdminAddress(String adminAddress) {
        this.adminAddress = adminAddress;
    }

    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getAdminContactNo() {
        return this.adminContactNo;
    }
    
    public void setAdminContactNo(String adminContactNo) {
        this.adminContactNo = adminContactNo;
    }

    public String getAdminStatus() {
        return this.adminStatus;
    }
    
    public void setAdminStatus(String adminStatus) {
        this.adminStatus = adminStatus;
    }
   








}