package com.kjnext.dmart.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Clients generated by MyEclipse - Hibernate Tools
 */

public class Clients  implements java.io.Serializable {


    // Fields    

    private Integer clientId;
    private UserDetail userDetail;
    private ClientDetails clientDetails;
    private String clientName;
    private Date createdDtm;
    private Date modifiedDtm;
    private Integer createdUId;
    private Integer modifiedUId;
    private DocumetRepository documetRepository;
    private String docname;
    private Set taskClientPointses = new HashSet(0);
    private Set taskses = new HashSet(0);
    private Set clientLocations = new HashSet(0);
    private Set userFeedbacks = new HashSet(0);
    
    private String clientFullName;


     @Override
    public String toString() {
    	
    	return clientName.toString();
    }

    // Constructors

    /** default constructor */
    public Clients() {
    }

	/** minimal constructor */
    public Clients(Integer clientId, String clientName) {
        this.clientId = clientId;
        this.clientName = clientName;
    }
    
    /** full constructor */
    public Clients(Integer clientId, UserDetail userDetail, ClientDetails clientDetails, String clientName, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId, Set taskClientPointses, Set taskses, Set clientLocations, Set userFeedbacks,DocumetRepository documetRepository,String docname) {
        this.clientId = clientId;
        this.userDetail = userDetail;
        this.clientDetails = clientDetails;
        this.clientName = clientName;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
        this.taskClientPointses = taskClientPointses;
        this.taskses = taskses;
        this.clientLocations = clientLocations;
        this.userFeedbacks = userFeedbacks;
        this.documetRepository = documetRepository;
        this.docname = docname;
    }

   
    // Property accessors

    public Integer getClientId() {
        return this.clientId;
    }
    
    public UserDetail getUserDetail() {
        return this.userDetail;
    }
    
    public void setUserDetail(UserDetail userDetail) {
        this.userDetail = userDetail;
    }

    public ClientDetails getClientDetails() {
        return this.clientDetails;
    }
    
    public void setClientDetails(ClientDetails clientDetails) {
        this.clientDetails = clientDetails;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }

    public Set getTaskClientPointses() {
        return this.taskClientPointses;
    }
    
    public void setTaskClientPointses(Set taskClientPointses) {
        this.taskClientPointses = taskClientPointses;
    }

    public Set getTaskses() {
        return this.taskses;
    }
    
    public void setTaskses(Set taskses) {
        this.taskses = taskses;
    }

    public Set getClientLocations() {
        return this.clientLocations;
    }
    
    public void setClientLocations(Set clientLocations) {
        this.clientLocations = clientLocations;
    }

    public Set getUserFeedbacks() {
        return this.userFeedbacks;
    }
    
    public void setUserFeedbacks(Set userFeedbacks) {
        this.userFeedbacks = userFeedbacks;
    }

	public DocumetRepository getDocumetRepository() {
		return documetRepository;
	}

	public void setDocumetRepository(DocumetRepository documetRepository) {
		this.documetRepository = documetRepository;
	}

	public String getDocname() {
		return docname;
	}

	public void setDocname(String docname) {
		this.docname = docname;
	}

	public String getClientFullName() {
		return clientFullName;
	}

	public void setClientFullName(String clientFullName) {
		this.clientFullName = clientFullName;
	}
   








}