package com.kjnext.dmart.hibernate;



/**
 * ClientDocuments generated by MyEclipse - Hibernate Tools
 */

public class ClientDocuments  implements java.io.Serializable {
    // Fields    

     private Integer clientDocid;
     private Integer clientId;
     private Integer docId;
     private String documentName;


    // Constructors

    /** default constructor */
    public ClientDocuments() {
    }

	/** minimal constructor */
    public ClientDocuments(Integer clientDocid) {
        this.clientDocid = clientDocid;
    }
    
    /** full constructor */
    public ClientDocuments(Integer clientDocid, Integer clientId, Integer docId, String documentName) {
        this.clientDocid = clientDocid;
        this.clientId = clientId;
        this.docId = docId;
        this.documentName = documentName;
    }

   
    // Property accessors

    public Integer getClientDocid() {
        return this.clientDocid;
    }
    
    public void setClientDocid(Integer clientDocid) {
        this.clientDocid = clientDocid;
    }

    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    public Integer getDocId() {
        return this.docId;
    }
    
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    public String getDocumentName() {
        return this.documentName;
    }
    
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }
   








}