package com.kjnext.dmart.hibernate;

import java.util.HashSet;
import java.util.Set;



/**
 * ClientDetails generated by MyEclipse - Hibernate Tools
 */

public class ClientDetails  implements java.io.Serializable {


    // Fields    

     private Integer cltDetailId;
     private Location location;
     private Users users;
     private String cltFirstName;
     private String cltLastName;
     private LocationArea locationArea;
     private String cltContactNo;
     private String cltEmail;
     private String cltStatus;
     private Set clients = new HashSet(0);

    // Constructors

    /** default constructor */
    public ClientDetails() {
    }

	
    
    /** full constructor */
    public ClientDetails(Integer cltDetailId, Location location, Users users, String cltFirstName, String cltLastName, LocationArea locationArea, String cltContactNo, String cltEmail, String cltStatus) {
        this.cltDetailId = cltDetailId;
        this.location = location;
        this.users = users;
        this.cltFirstName = cltFirstName;
        this.cltLastName = cltLastName;
        this.locationArea = locationArea;
        this.cltContactNo = cltContactNo;
        this.cltEmail = cltEmail;
        this.cltStatus = cltStatus;
    }

   
    // Property accessors

   

    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    public String getCltFirstName() {
        return this.cltFirstName;
    }
    
    public void setCltFirstName(String cltFirstName) {
        this.cltFirstName = cltFirstName;
    }

    public String getCltLastName() {
        return this.cltLastName;
    }
    
    public void setCltLastName(String cltLastName) {
        this.cltLastName = cltLastName;
    }

    public LocationArea getlocationArea() {
        return this.locationArea;
    }
    
    public void setlocationArea(LocationArea locationArea) {
        this.locationArea = locationArea;
    }

    public String getCltContactNo() {
        return this.cltContactNo;
    }
    
    public void setCltContactNo(String cltContactNo) {
        this.cltContactNo = cltContactNo;
    }

    public String getCltEmail() {
        return this.cltEmail;
    }
    
    public void setCltEmail(String cltEmail) {
        this.cltEmail = cltEmail;
    }

    public String getCltStatus() {
        return this.cltStatus;
    }
    
    public void setCltStatus(String cltStatus) {
        this.cltStatus = cltStatus;
    }



	public Integer getCltDetailId() {
		return cltDetailId;
	}



	public void setCltDetailId(Integer cltDetailId) {
		this.cltDetailId = cltDetailId;
	}

	

	public Set getClients() {
		return clients;
	}



	public void setClients(Set clients) {
		this.clients = clients;
	}
   








}