package com.kjnext.dmart.hibernate;

import java.util.Date;


/**
 * ClientLocation generated by MyEclipse - Hibernate Tools
 */

public class ClientLocation  implements java.io.Serializable {


    // Fields    

     private Integer clientLocId;
     private Clients clients;
     private Location location;
     private Date createdDtm;
     private Date modifiedDtm;
     private Integer createdUId;
     private Integer modifiedUId;


    // Constructors

    /** default constructor */
    public ClientLocation() {
    }

	/** minimal constructor */
    public ClientLocation(Integer clientLocId, Clients clients, Location location) {
        this.clientLocId = clientLocId;
        this.clients = clients;
        this.location = location;
    }
    
    /** full constructor */
    public ClientLocation(Integer clientLocId, Clients clients, Location location, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId) {
        this.clientLocId = clientLocId;
        this.clients = clients;
        this.location = location;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
    }

   
    // Property accessors

    public Integer getClientLocId() {
        return this.clientLocId;
    }
    
    public void setClientLocId(Integer clientLocId) {
        this.clientLocId = clientLocId;
    }

    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }
   








}