package com.kjnext.dmart.hibernate;

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumetRepository generated by MyEclipse - Hibernate Tools
 */

public class DocumetRepository implements java.io.Serializable {

	// Fields

	private Integer docId;

	private Blob document;

	private Set userDocumentses = new HashSet(0);

	private Set feedbackDocumentses = new HashSet(0);

	// Constructors

	/** default constructor */
	public DocumetRepository() {
	}

	/** minimal constructor */
	public DocumetRepository(Integer docId, Blob document) {
		this.docId = docId;
		this.document = document;
	}

	/** full constructor */
	public DocumetRepository(Integer docId, Blob document,
			Set userDocumentses, Set feedbackDocumentses) {
		this.docId = docId;
		this.document = document;
		this.userDocumentses = userDocumentses;
		this.feedbackDocumentses = feedbackDocumentses;
	}

	// Property accessors

	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	public Blob getDocument() {
		return this.document;
	}

	public void setDocument(Blob document) {
		this.document = document;
	}

	public Set getUserDocumentses() {
		return this.userDocumentses;
	}

	public void setUserDocumentses(Set userDocumentses) {
		this.userDocumentses = userDocumentses;
	}

	public Set getFeedbackDocumentses() {
		return this.feedbackDocumentses;
	}

	public void setFeedbackDocumentses(Set feedbackDocumentses) {
		this.feedbackDocumentses = feedbackDocumentses;
	}

}