package com.kjnext.dmart.hibernate;

import java.util.Date;


/**
 * FeedbackDocuments generated by MyEclipse - Hibernate Tools
 */

public class FeedbackDocuments  implements java.io.Serializable {


    // Fields    

     private Integer feedbackDocId;
     private UserFeedback userFeedback;
     private DocumetRepository documetRepository;
     private String documentName;
     private Date createdDtm;
     private Date modifiedDtm;
     private Integer createdUId;
     private Integer modifiedUId;
     private String documentStatus;


    // Constructors

    /** default constructor */
    public FeedbackDocuments() {
    }

	/** minimal constructor */
    public FeedbackDocuments(Integer feedbackDocId) {
        this.feedbackDocId = feedbackDocId;
    }
    
    /** full constructor */
    public FeedbackDocuments(Integer feedbackDocId, UserFeedback userFeedback, DocumetRepository documetRepository, String documentName, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId,String documentStatus) {
        this.feedbackDocId = feedbackDocId;
        this.userFeedback = userFeedback;
        this.documetRepository = documetRepository;
        this.documentName = documentName;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
        this.documentStatus = documentStatus;
    }

   
    // Property accessors

    public Integer getFeedbackDocId() {
        return this.feedbackDocId;
    }
    
    public void setFeedbackDocId(Integer feedbackDocId) {
        this.feedbackDocId = feedbackDocId;
    }

    public UserFeedback getUserFeedback() {
        return this.userFeedback;
    }
    
    public void setUserFeedback(UserFeedback userFeedback) {
        this.userFeedback = userFeedback;
    }

    public DocumetRepository getDocumetRepository() {
        return this.documetRepository;
    }
    
    public void setDocumetRepository(DocumetRepository documetRepository) {
        this.documetRepository = documetRepository;
    }

    public String getDocumentName() {
        return this.documentName;
    }
    
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }

	public String getDocumentStatus() {
		return documentStatus;
	}

	public void setDocumentStatus(String documentStatus) {
		this.documentStatus = documentStatus;
	}
   








}