package com.kjnext.dmart.hibernate;

import java.util.Date;

import com.kjnext.dmart.hibernate.UserDetail;

/**
 * HistoryUserDetail generated by MyEclipse - Hibernate Tools
 */

public class HistoryUserDetail implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer srNo;

	private UserDetail userDetailByForUser;//this is for userEmpId

	private UserDetail userDetailByUid;//this is for uid

	private Date dtm;

	private String oldValue;

	private String newValue;

	private String function;

	private String columnName;

	// Constructors

	/** default constructor */
	public HistoryUserDetail() {
	}

	/** minimal constructor */
	public HistoryUserDetail(Integer srNo, Date dtm) {
		this.srNo = srNo;
		this.dtm = dtm;
	}

	/** full constructor */
	public HistoryUserDetail(Integer srNo, UserDetail userDetailByForUser,
			UserDetail userDetailByUid, Date dtm, String oldValue,
			String newValue, String function, String columnName) {
		this.srNo = srNo;
		this.userDetailByForUser = userDetailByForUser;
		this.userDetailByUid = userDetailByUid;
		this.dtm = dtm;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.function = function;
		this.columnName = columnName;
	}

	// Property accessors

	public Integer getSrNo() {
		return this.srNo;
	}

	public void setSrNo(Integer srNo) {
		this.srNo = srNo;
	}

	public UserDetail getUserDetailByForUser() {
		return this.userDetailByForUser;
	}

	public void setUserDetailByForUser(UserDetail userDetailByForUser) {
		this.userDetailByForUser = userDetailByForUser;
	}

	public UserDetail getUserDetailByUid() {
		return this.userDetailByUid;
	}

	public void setUserDetailByUid(UserDetail userDetailByUid) {
		this.userDetailByUid = userDetailByUid;
	}

	public Date getDtm() {
		return this.dtm;
	}

	public void setDtm(Date dtm) {
		this.dtm = dtm;
	}

	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

}