package com.kjnext.dmart.hibernate;

import java.util.Date;


/**
 * History generated by MyEclipse - Hibernate Tools
 */

public class History  implements java.io.Serializable {


    // Fields    

     private Integer srNo;
     private UserDetail userDetail;
     private Date dtm;
     private String oldValue;
     private String newValue;
     private String function;
     private String columnName;


    // Constructors

    /** default constructor */
    public History() {
    }

	/** minimal constructor */
    public History(Integer srNo, Date dtm) {
        this.srNo = srNo;
        this.dtm = dtm;
    }
    
    /** full constructor */
    public History(Integer srNo, UserDetail userDetail, Date dtm, String oldValue, String newValue, String function, String columnName) {
        this.srNo = srNo;
        this.userDetail = userDetail;
        this.dtm = dtm;
        this.oldValue = oldValue;
        this.newValue = newValue;
        this.function = function;
        this.columnName = columnName;
    }

   
    // Property accessors

    public Integer getSrNo() {
        return this.srNo;
    }
    
    public void setSrNo(Integer srNo) {
        this.srNo = srNo;
    }

    public UserDetail getUserDetail() {
        return this.userDetail;
    }
    
    public void setUserDetail(UserDetail userDetail) {
        this.userDetail = userDetail;
    }

    public Date getDtm() {
        return this.dtm;
    }
    
    public void setDtm(Date dtm) {
        this.dtm = dtm;
    }

    public String getOldValue() {
        return this.oldValue;
    }
    
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }

    public String getNewValue() {
        return this.newValue;
    }
    
    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    public String getFunction() {
        return this.function;
    }
    
    public void setFunction(String function) {
        this.function = function;
    }

    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
   








}