package com.kjnext.dmart.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Location generated by MyEclipse - Hibernate Tools
 */

public class Location  implements java.io.Serializable {


    // Fields    

    // Constructors
	private Integer locId;
	private String country;
	private String state;
	private String city;
	private String area;
	private Date createdDtm;
	private Date modifiedDtm;
	private Integer createdUId;
	private Integer modifiedUId;
	private String status;
	private Set clientLocations = new HashSet(0);
	private Set taskses = new HashSet(0);
	private Set userDetails = new HashSet(0);
	private Set locationAreas = new HashSet(0);
	private String cityAndArea;
	
	private String modifiedUIdName;
	private String createdUIdName;

    /** default constructor */
    public Location() {
    }

	/** minimal constructor */
    public Location(Integer locId) {
        this.locId = locId;
    }
    
    /** full constructor */
    public Location(Integer locId, String country, String state, String city, String area, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId, Set clientLocations, Set taskses, Set userDetails,String status) {
        this.locId = locId;
        this.country = country;
        this.state = state;
        this.city = city;
        this.area = area;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
        this.clientLocations = clientLocations;
        this.taskses = taskses;
        this.userDetails = userDetails;
        this.status = status;
    }

   
    // Property accessors

    public Integer getLocId() {
        return this.locId;
    }
    
    public void setLocId(Integer locId) {
        this.locId = locId;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }

    public Set getClientLocations() {
        return this.clientLocations;
    }
    
    public void setClientLocations(Set clientLocations) {
        this.clientLocations = clientLocations;
    }

    public Set getTaskses() {
        return this.taskses;
    }
    
    public void setTaskses(Set taskses) {
        this.taskses = taskses;
    }

    public Set getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(Set userDetails) {
        this.userDetails = userDetails;
    }

	public String getCityAndArea() {
		return cityAndArea;
	}

	public void setCityAndArea(String cityAndArea) {
		this.cityAndArea = cityAndArea;
	}

	public Set getLocationAreas() {
		return locationAreas;
	}

	public void setLocationAreas(Set locationAreas) {
		this.locationAreas = locationAreas;
	}

	public String getCreatedUIdName() {
		return createdUIdName;
	}

	public void setCreatedUIdName(String createdUIdName) {
		this.createdUIdName = createdUIdName;
	}

	public String getModifiedUIdName() {
		return modifiedUIdName;
	}

	public void setModifiedUIdName(String modifiedUIdName) {
		this.modifiedUIdName = modifiedUIdName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}








}