package com.kjnext.dmart.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * LocationArea generated by MyEclipse - Hibernate Tools
 */

public class LocationArea  implements java.io.Serializable {


    // Fields    

     private Integer areaId;
     private Location location;
     private String areaName;
     private String areaStatus;
     private Set userDetails = new HashSet(0);
     private Set clientDetailses = new HashSet(0);


    // Constructors

    /** default constructor */
    public LocationArea() {
    }

	/** minimal constructor */
    public LocationArea(Integer areaId) {
        this.areaId = areaId;
    }
    
    /** full constructor */
    public LocationArea(Integer areaId, Location location, String areaName, Set userDetails, Set clientDetailses,String areaStatus) {
        this.areaId = areaId;
        this.location = location;
        this.areaName = areaName;
        this.userDetails = userDetails;
        this.clientDetailses = clientDetailses;
        this.areaStatus = areaStatus;
    }

   
    // Property accessors

    public Integer getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public Set getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(Set userDetails) {
        this.userDetails = userDetails;
    }

    public Set getClientDetailses() {
        return this.clientDetailses;
    }
    
    public void setClientDetailses(Set clientDetailses) {
        this.clientDetailses = clientDetailses;
    }

	public String getAreaStatus() {
		return areaStatus;
	}

	public void setAreaStatus(String areaStatus) {
		this.areaStatus = areaStatus;
	}

	

}