package com.kjnext.dmart.hibernate;

import java.util.Date;


/**
 * TaskClientPoints generated by MyEclipse - Hibernate Tools
 */

public class TaskClientPoints  implements java.io.Serializable {


    // Fields    

     private Integer taskPointId;
     private Clients clients;
     private Integer taskPoints;
     private Date createdDtm;
     private Date modifiedDtm;
     private Integer createdUId;
     private Integer modifiedUId;


     
   //non fields by amarjit
     private String modifiedUIdName;
     private String createdUIdName;
     
    // Constructors

    public String getModifiedUIdName() {
		return modifiedUIdName;
	}

	public void setModifiedUIdName(String modifiedUIdName) {
		this.modifiedUIdName = modifiedUIdName;
	}

	public String getCreatedUIdName() {
		return createdUIdName;
	}

	public void setCreatedUIdName(String createdUIdName) {
		this.createdUIdName = createdUIdName;
	}

	/** default constructor */
    public TaskClientPoints() {
    }

	/** minimal constructor */
    public TaskClientPoints(Integer taskPointId) {
        this.taskPointId = taskPointId;
    }
    
    /** full constructor */
    public TaskClientPoints(Integer taskPointId, Clients clients, Integer taskPoints, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId) {
        this.taskPointId = taskPointId;
        this.clients = clients;
        this.taskPoints = taskPoints;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
    }

   
    // Property accessors

    public Integer getTaskPointId() {
        return this.taskPointId;
    }
    
    public void setTaskPointId(Integer taskPointId) {
        this.taskPointId = taskPointId;
    }

    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

    public Integer getTaskPoints() {
        return this.taskPoints;
    }
    
    public void setTaskPoints(Integer taskPoints) {
        this.taskPoints = taskPoints;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }
   








}