package com.kjnext.dmart.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * UserDetail generated by MyEclipse - Hibernate Tools
 */


public class UserDetail  implements java.io.Serializable {


    // Fields    

     private Integer userEmpId;
     private Location location;
     private Users users;
     private String firstName;
     private String lastName;
     private LocationArea locationArea;
     private String contactNo;
     private String emailId;
     private String status;
     private String statusLabel;
     private String gender;
     private Date createdDtm;
     private Date modifiedDtm;
     private Integer createdUId;
     private Integer modifiedUId;
     private String verificationId;
     private Set userDocumentses = new HashSet(0);
     private Set userFeedbacks = new HashSet(0);
     private Set taskses = new HashSet(0);
     private Set userRewardses = new HashSet(0);
     private Set clients = new HashSet(0);
     private Date expiryDate;
     private String modifiedUIdName;
     private String createdUIdName;
  
     private String nameAndLocation ;
     private String address;
     private String message;
     private String city;
     
     private Integer[] userEmployeeId;

     public Integer[] getUserEmployeeId() {
		return userEmployeeId;
	}

	public void setUserEmployeeId(Integer[] userEmployeeId) {
		this.userEmployeeId = userEmployeeId;
	}

	@Override
    public String toString() {
		if(firstName!=null )
			return firstName.concat(" "+lastName).toString();
		else
			return "";
    }

    // Constructors

	/** default constructor */
    public UserDetail() {
    }

	/** minimal constructor */
    public UserDetail(Integer userEmpId) {
        this.userEmpId = userEmpId;
    }
    
    /** full constructor */
    public UserDetail(Integer userEmpId, Location location, Users users, String firstName, String lastName, LocationArea locationArea, String contactNo, String emailId, String status, String gender, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId, String verificationId, Set userDocumentses, Set userFeedbacks, Set taskses, Set userRewardses) {
        this.userEmpId = userEmpId;
        this.location = location;
        this.users = users;
        this.firstName = firstName;
        this.lastName = lastName;
        this.locationArea = locationArea;
        this.contactNo = contactNo;
        this.emailId = emailId;
        this.status = status;
        this.gender = gender;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
        this.verificationId = verificationId;
        this.userDocumentses = userDocumentses;
        this.userFeedbacks = userFeedbacks;
        this.taskses = taskses;
        this.userRewardses = userRewardses;
    }

   
    // Property accessors

    public Integer getUserEmpId() {
        return this.userEmpId;
    }
    
    public void setUserEmpId(Integer userEmpId) {
    	
    	if(userEmpId !=null && userEmpId<0){
    		this.userEmpId	=0;
    	}else{
    		this.userEmpId = userEmpId;
    	}
    }

    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public LocationArea getlocationArea() {
        return this.locationArea;
    }
    
    public void setlocationArea(LocationArea locationArea) {
        this.locationArea = locationArea;
    }

    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }

    public String getVerificationId() {
        return this.verificationId;
    }
    
    public void setVerificationId(String verificationId) {
        this.verificationId = verificationId;
    }

    public Set getUserDocumentses() {
        return this.userDocumentses;
    }
    
    public void setUserDocumentses(Set userDocumentses) {
        this.userDocumentses = userDocumentses;
    }

    public Set getUserFeedbacks() {
        return this.userFeedbacks;
    }
    
    public void setUserFeedbacks(Set userFeedbacks) {
        this.userFeedbacks = userFeedbacks;
    }

    public Set getTaskses() {
        return this.taskses;
    }
    
    public void setTaskses(Set taskses) {
        this.taskses = taskses;
    }

    public Set getUserRewardses() {
        return this.userRewardses;
    }
    
    public void setUserRewardses(Set userRewardses) {
        this.userRewardses = userRewardses;
    }
   
    public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getModifiedUIdName() {
		return modifiedUIdName;
	}

	public void setModifiedUIdName(String modifiedUIdName) {
		this.modifiedUIdName = modifiedUIdName;
	}

	public String getCreatedUIdName() {
		return createdUIdName;
	}

	public void setCreatedUIdName(String createdUIdName) {
		this.createdUIdName = createdUIdName;
	}

	public Set getClients() {
		return clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

	/**
	 * @return the statusLabel
	 */
	public String getStatusLabel() {
		if("PENDING_USER".equals(getStatus())){
			statusLabel="Pending Approval"; 
		}
		if("APPROVED_USER".equals(getStatus())){
			statusLabel="Waiting User for varificationID"; 
		}
		if("ACTIVE".equals(getStatus())){
			statusLabel="Active"; 
		}
		if("INACTIVE".equals(getStatus())){
			statusLabel="Suspended"; 
		}
		if("APPROVED_USER".equals(getStatus())){
			statusLabel="Waiting User for varificationID"; 
		}
		return statusLabel;
	}

	/**
	 * @return the locationLabel
	 */
	public String getLocationLabel() {
		return getLocation().getCity()+"-"+getlocationArea().getAreaName();
	}
	public String getNameLabel() {
		return getFirstName()+" "+getLastName();
	}

	public String getNameAndLocation() {
		return getNameLabel()+" : "+getLocationLabel();
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getCity() {
		return city;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return super.hashCode();
	}

	public void setCity(String city) {
		this.city = city;
	}

	






}