package com.kjnext.dmart.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Users generated by MyEclipse - Hibernate Tools
 */

public class Users  implements java.io.Serializable {


    // Fields    

     private Integer uid;
     private String uname;
     private String upass;
     private String utype;
     private Date createdDtm;
     private Date modifiedDtm;
     private String lastAccessedTime;
     private Set userDetails = new HashSet(0);


    // Constructors

    /** default constructor */
    public Users() {
    }

	/** minimal constructor */
    public Users(Integer uid) {
        this.uid = uid;
    }
    
    /** full constructor */
    public Users(Integer uid, String uname, String upass, String utype, Date createdDtm, Date modifiedDtm, Set userDetails) {
        this.uid = uid;
        this.uname = uname;
        this.upass = upass;
        this.utype = utype;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.userDetails = userDetails;
    }

   
    // Property accessors

    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getUpass() {
        return this.upass;
    }
    
    public void setUpass(String upass) {
        this.upass = upass;
    }

    public String getUtype() {
        return this.utype;
    }
    
    public void setUtype(String utype) {
        this.utype = utype;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Set getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(Set userDetails) {
        this.userDetails = userDetails;
    }

	/**
	 * @return the lastAccessedTime
	 */
	public String getLastAccessedTime() {
		return lastAccessedTime;
	}

	/**
	 * @param lastAccessedTime the lastAccessedTime to set
	 */
	public void setLastAccessedTime(String lastAccessedTime) {
		this.lastAccessedTime = lastAccessedTime;
	}









}