package com.kjnext.dmart.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * UserFeedback generated by MyEclipse - Hibernate Tools
 */

public class UserFeedback  implements java.io.Serializable {


    // Fields    

     private Integer feedbackId;
     private UserDetail userDetail;
     private Tasks tasks;
     private Clients clients;
     private String taskAssignProof;
     private String feedbackDetails;
     private String status;
     private Date createdDtm;
     private Date modifiedDtm;
     private Integer createdUId;
     private Integer modifiedUId;
     private String sentStatus;
     private Set feedbackDocumentses = new HashSet(0);
     private Date sentDtm;
     
     private String remarkByClient;
     
     
     
//   non fields by amarjit
     private String modifiedUIdName;
     private String createdUIdName;
     private String taskUserStatus;
     private String feedSentStatus;
     private Integer unsentCount;
 	 private Integer sentCount;
 	 private Integer allCount;
 	 private String clientname;
 	
     
     

	public String getFeedSentStatus() {
		return feedSentStatus;
	}

	public void setFeedSentStatus(String feedSentStatus) {
		this.feedSentStatus = feedSentStatus;
	}

	public String getTaskUserStatus() {
		return taskUserStatus;
	}

	public void setTaskUserStatus(String taskUserStatus) {
		this.taskUserStatus = taskUserStatus;
	}

	
	public String getModifiedUIdName() {
		return modifiedUIdName;
	}

	public void setModifiedUIdName(String modifiedUIdName) {
		this.modifiedUIdName = modifiedUIdName;
	}

	public String getCreatedUIdName() {
		return createdUIdName;
	}

	public void setCreatedUIdName(String createdUIdName) {
		this.createdUIdName = createdUIdName;
	}

	
     
    // Constructors

    /** default constructor */
    public UserFeedback() {
    }

	/** minimal constructor */
    public UserFeedback(Integer feedbackId, Date modifiedDtm, Integer createdUId) {
        this.feedbackId = feedbackId;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
    }
    
    /** full constructor */
    public UserFeedback(Integer feedbackId, UserDetail userDetail, Tasks tasks, Clients clients, String taskAssignProof, String feedbackDetails, String status, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId, Set feedbackDocumentses,String remarkByClient) {
        this.feedbackId = feedbackId;
        this.userDetail = userDetail;
        this.tasks = tasks;
        this.clients = clients;
        this.taskAssignProof = taskAssignProof;
        this.feedbackDetails = feedbackDetails;
        this.status = status;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
        this.feedbackDocumentses = feedbackDocumentses;
        this.remarkByClient = remarkByClient;
    }

   
    // Property accessors

    public Integer getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    public UserDetail getUserDetail() {
        return this.userDetail;
    }
    
    public void setUserDetail(UserDetail userDetail) {
        this.userDetail = userDetail;
    }

    public Tasks getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Tasks tasks) {
        this.tasks = tasks;
    }

    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

    public String getTaskAssignProof() {
        return this.taskAssignProof;
    }
    
    public void setTaskAssignProof(String taskAssignProof) {
        this.taskAssignProof = taskAssignProof;
    }

    public String getFeedbackDetails() {
        return this.feedbackDetails;
    }
    
    public void setFeedbackDetails(String feedbackDetails) {
        this.feedbackDetails = feedbackDetails;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }

    public Set getFeedbackDocumentses() {
        return this.feedbackDocumentses;
    }
    
    public void setFeedbackDocumentses(Set feedbackDocumentses) {
        this.feedbackDocumentses = feedbackDocumentses;
    }

	public String getSentStatus() {
		return sentStatus;
	}

	public void setSentStatus(String sentStatus) {
		this.sentStatus = sentStatus;
	}

	public Integer getUnsentCount() {
		return unsentCount;
	}

	public void setUnsentCount(Integer unsentCount) {
		this.unsentCount = unsentCount;
	}

	public Integer getSentCount() {
		return sentCount;
	}

	public void setSentCount(Integer sentCount) {
		this.sentCount = sentCount;
	}

	public Integer getAllCount() {
		return allCount;
	}

	public void setAllCount(Integer allCount) {
		this.allCount = allCount;
	}

	public String getClientname() {
		return clientname;
	}

	public void setClientname(String clientname) {
		this.clientname = clientname;
	}

	public Date getSentDtm() {
		return sentDtm;
	}

	public void setSentDtm(Date sentDtm) {
		this.sentDtm = sentDtm;
	}

	public String getStatusLabel() {
		if("INITIATED_ADMIN".equals(getStatus())){
			return "Task Assigned by Admin"; 
		}
		if("INITIATED_USER".equals(getStatus())){
			return "Task Accepted by Agent"; 
		}
		if("FINISHED_USER".equals(getStatus())){
			return "Feedback Submitted by Agent"; 
		}
		if("FINISHED_ADMIN".equals(getStatus())){
			return "Feedback Approved "; 
		}
		if("REJECTED_ADMIN".equals(getStatus())){
			return "Feedback Rejected"; 
		}
		return "Pending"; 
	}

	public String getRemarkByClient() {
		return remarkByClient;
	}

	public void setRemarkByClient(String remarkByClient) {
		this.remarkByClient = remarkByClient;
	}

}