package com.kjnext.dmart.hibernate;

import java.util.Date;


/**
 * UserRewards generated by MyEclipse - Hibernate Tools
 */

public class UserRewards  implements java.io.Serializable {


    // Fields    

     private Integer rewardId;
     private UserDetail userDetail;
     private String point;
     private Date createdDtm;
     private Date modifiedDtm;
     private Integer createdUId;
     private Integer modifiedUId;
     private String redeemPoint;
     private String requestRedeemPoint;
     private String remarks;
     private String modeOfPayment;
     
     
     public String getRedeemPoint() {
		return redeemPoint;
	}

	public void setRedeemPoint(String redeemPoint) {
		this.redeemPoint = redeemPoint;
	}

	//non fields by amarjit
     private String modifiedUIdName;
     private String createdUIdName;


    // Constructors

    public String getModifiedUIdName() {
		return modifiedUIdName;
	}

	public void setModifiedUIdName(String modifiedUIdName) {
		this.modifiedUIdName = modifiedUIdName;
	}

	public String getCreatedUIdName() {
		return createdUIdName;
	}

	public void setCreatedUIdName(String createdUIdName) {
		this.createdUIdName = createdUIdName;
	}

	/** default constructor */
    public UserRewards() {
    }

	/** minimal constructor */
    public UserRewards(Integer rewardId, UserDetail userDetail, String point) {
        this.rewardId = rewardId;
        this.userDetail = userDetail;
        this.point = point;
    }
    
    /** full constructor */
    public UserRewards(Integer rewardId, UserDetail userDetail, String point, Date createdDtm, Date modifiedDtm, Integer createdUId, Integer modifiedUId) {
        this.rewardId = rewardId;
        this.userDetail = userDetail;
        this.point = point;
        this.createdDtm = createdDtm;
        this.modifiedDtm = modifiedDtm;
        this.createdUId = createdUId;
        this.modifiedUId = modifiedUId;
    }

   
    // Property accessors

    public Integer getRewardId() {
        return this.rewardId;
    }
    
    public void setRewardId(Integer rewardId) {
        this.rewardId = rewardId;
    }

    public UserDetail getUserDetail() {
        return this.userDetail;
    }
    
    public void setUserDetail(UserDetail userDetail) {
        this.userDetail = userDetail;
    }

    public String getPoint() {
        return this.point;
    }
    
    public void setPoint(String point) {
        this.point = point;
    }

    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    public Date getModifiedDtm() {
        return this.modifiedDtm;
    }
    
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    public Integer getCreatedUId() {
        return this.createdUId;
    }
    
    public void setCreatedUId(Integer createdUId) {
        this.createdUId = createdUId;
    }

    public Integer getModifiedUId() {
        return this.modifiedUId;
    }
    
    public void setModifiedUId(Integer modifiedUId) {
        this.modifiedUId = modifiedUId;
    }

	public String getRequestRedeemPoint() {
		return requestRedeemPoint;
	}

	public void setRequestRedeemPoint(String requestRedeemPoint) {
		this.requestRedeemPoint = requestRedeemPoint;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getModeOfPayment() {
		return modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}
   








}