/**
 * 
 */
package com.kjnext.dmart.vo;

/**
 * @author Kiran
 * 
 */
public enum Status {
	
	ACTIVE, INACTIVE, INITIATED_ADMIN, INITIATED_USER, FINISHED_USER, FINISHED_ADMIN, INITIATED_CLIENT, 
	FINISHED_CLIENT, REJECTED_ADMIN, REJECTED_USER, REJECTED_CLIENT,APPROVED_USER,PENDING_USER,INACTIVATED_ADMIN,
	FEEDBACK_OFFLINE,INITIATED_ADMIN_MULTIUSER,INITIATED_USER_MULTIUSER_ACCEPT,INITIATED_USER_MULTIUSER_REJECT,REJECTED_TASK,
	BILL_UPLOAD,IMAGE_UPLOAD,OTHER_DOC_UPLOAD,OFFLINE_DOC_UPLOAD,REASSIGNED_BY_CLIENT





}











